include = ["wvw/**/*.py", "tests/**/*.py"]
exclude = ["**/__pycache__/**"]
fix = true
line-length = 180

[lint]
extend-select = ["E"]
#logger-objects = ["wvw.main.logger"]
task-tags = ["TODO", "BUG", "HACK"]
#typing-modules = ["wvw.types"]

[lint.flake8-bandit]
hardcoded-tmp-directory = []

#[lint.flake8-builtins]
#builtins-allowed-modules = ["id"]

[lint.flake8-copyright]
author = "Alexander Auras"

[lint.flake8-errmsg]
max-string-length = 20

[lint.flake8-implicit-str-concat]
allow-multiline = false

[lint.flake8-import-conventions.aliases]
"matplotlib" = "mpl"
"matplotlib.pyplot" = "plt"
"numpy" = "np"
"numpy.typing" = "npt"
"pandas" = "pd"
"torch.nn" = "nn"
"torch.nn.functional" = "F"
"scipy" = "sp"
"PIL.Image" = "Image"

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

#[lint.flake8-tidy-imports.banned-api]
#"typing" = "Use pydantic.typing instead"

[lint.flake8-type-checking]
#exempt-modules = "wvw.types"
strict = true

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
lines-after-imports = 2

[lint.pydocstyle]
convention = "google"
